.PHONY: all sandbox

all: sandbox

sandbox:
	rm -rf sandbox
	mkdir sandbox
	touch \
		sandbox/Hello\ au\ 2023-10-15.pdf \
		sandbox/Hello\ 2023-10-15.pdf \
		sandbox/IMG-20231117-whatever.jpg \
		sandbox/IMG-20231117-another.jpg
