# Specify whether we should prefix by date and time (true) or just by date
# (false)
# time = false

# Configure the default format for the two possible values of `time`
[default_format]
# date = "%Y-%m-%d"
# date_time = "%Y-%m-%d %Hh%Mm%S"

# Enable/disable the metadata matchers
[matchers.metadata]
# created = false
# modified = false

# Enable/disable pseudo-matchers that work with pre-determined date
[matchers.predetermined_date]
# today = false

# All values defined under matchers.patterns.* configure a pattern matcher

[matchers.patterns.ymd_date_suffix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[\\ _-]?
  (?<month>\\d{2})[\\ _-]?
  (?<day>\\d{2})
  \\z
"""

[matchers.patterns.dmy_date_suffix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<day>\\d{2})[\\ _-]?
  (?<month>\\d{2})[\\ _-]?
  (?<year>\\d{4})
  \\z
"""

[matchers.patterns.ymd_date_infix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<end>.+)
  \\z
"""

[matchers.patterns.dmy_date_infix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<day>\\d{2})[-]?
  (?<month>\\d{2})[-]?
  (?<year>\\d{4})[\\ _-]
  (?<end>.+)
  \\z
"""

[matchers.patterns.date_time_infix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<hour>\\d{2})[h]?
  (?<min>\\d{2})[m]?
  (?<sec>\\d{2})[s\\ _-]?
  (?<end>.+)
  \\z
"""
time = true

[matchers.patterns.date_time_suffix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<hour>\\d{2})[h]?
  (?<min>\\d{2})[m]?
  (?<sec>\\d{2})[s]?
  \\z
"""
time = true

[matchers.patterns.whatsapp_image]
regex = """
  \\A
  .+[\\ _-]
  (?<year>\\d{4})-
  (?<month>\\d{2})-
  (?<day>\\d{2})\\s
  at\\s
  (?<hour>\\d{2}).
  (?<min>\\d{2}).
  (?<sec>\\d{2})
  \\z
"""
time = true
