[cic]
regex = """
  \\A
  (?<rest>.+)
  \\s+au\\s+
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})
  \\z
"""

[date_suffix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})
  \\z
"""

[date_infix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<end>.+)
  \\z
"""

[date_time_infix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<hour>\\d{2})[h]?
  (?<min>\\d{2})[m]?
  (?<sec>\\d{2})[s\\ _-]?
  (?<end>.+)
  \\z
"""
time = true

[date_time_suffix]
regex = """
  \\A
  (?<start>.+)[\\ _-]
  (?<year>\\d{4})[-]?
  (?<month>\\d{2})[-]?
  (?<day>\\d{2})[\\ _-]
  (?<hour>\\d{2})[h]?
  (?<min>\\d{2})[m]?
  (?<sec>\\d{2})[s]?
  \\z
"""
time = true
