[cic]
regex = """
  (?<rest>.+)
  \\s+au\\s+
  (?<year>\\d{4})
  -
  (?<month>\\d{2})
  -
  (?<day>\\d{2})
"""
delimiter = " "

[whatsapp]
regex = """
  (?<start>[A-Z]+)-
  (?<year>\\d{4})
  (?<month>\\d{2})
  (?<day>\\d{2})
  -
  (?<end>.+)
"""
delimiter = " "

[datesuffix]
regex = """
  (?<start>[A-Za-z0-9 _-]+)[ _-]
  (?<year>\\d{4})
  (?<month>\\d{2})
  (?<day>\\d{2})
"""
delimiter = " "

[dateinfix]
regex = """
  (?<start>.+)[ _-]
  (?<year>\\d{4})-?
  (?<month>\\d{2})-?
  (?<day>\\d{2})
  [ _-](?<end>.+)
"""
delimiter = " "
